import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my blog
        </h1>

        <p className={styles.description}>
          {
            props.data.map(item => (
            <div>
            <p>{item['header']}</p> 
            <p>{item['body']}</p>
            </div>
            ))
          }
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/johan-new/backendless-blog"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Backendless Blog
        </a>
      </footer>
    </div>
  )
}
 export async function getStaticProps(context) {

  const res = await fetch('https://raw.githubusercontent.com/johan-new/blog-content/main/content.json')
  const data = await res.json();

   return {
     props: {
       data
     },
   }
 }